version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/django-ecommerce

hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/restart.sh
      timeout: 300
      runas: root
